server:
  port: 8081
  shutdown: graceful

service:
  environment: local

spring:
  application:
    name: meal-mate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jackson:
    time-zone: Asia/Seoul
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          default_batch_fetch_size: 1000

    servlet:
      multipart:
        max-file-size: 200MB
        max-request-size: 200MB

feign:
  client:app:
    config:
      default:
        loggerLevel: full

app:
  cors:
    allowedOrigins: https://localhost:8080, https://localhost:8081, http://localhost:3000

logging:
  level:
    org.hibernate:
      type: debug
    org.springframework.web.client: trace

management:
  endpoints:
    web:
      exposure:
        include: health

swagger:
  ui:
    path: classpath:/static/docs/